M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-06-02T15:32:42+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-02T15:32:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X192.982Y-108.61
X192.982Y-114.39
M30
